### ISSUE TITLE
Closure example, working MWE?

### ISSUE THREAD

**Issue by bardo84** [m3g/JuliaCookBook.jl#5]
Hi,

I tried to put your [example ](https://m3g.github.io/JuliaNotes.jl/stable/closures/#Example)into a running code:

```
function solver(f,x)
    y = f(x)
    return y
end

a = 5
f(x,a) = a*x

# closure
g(x) = f(x,a,b,c)
a = 1; b = 2; c = 3;
x = 5.0;
solver(g, x)
```

Obviously, the f defined several lines above is not fitting to the call.
Could you provide a suitable f() to produce the shown result?
Thx

**Comment by lmiq** [comment]
Actually it is `g` that must be defined after `a`, `b` and `c`. Because it closes over those values. I will fix that.

**Comment by lmiq** [comment]
I've updated the examples here, if you find any issue, please let me know: https://m3g.github.io/JuliaNotes.jl/stable/closures/

**Comment by bardo84** [comment]
Thx, pls see a related question on [discourse](https://discourse.julialang.org/t/closures-pass-by-value-or-reference/71155/2).
