### ISSUE TITLE
anonymous function and scope

### ISSUE THREAD

**Issue by PaulSoderlind** [m3g/JuliaCookBook.jl#7]
Thanks for the JuliaNotes.jl.

A short comment on anonymous functions: it's all about global scope.
 
For instance, when the anonymous function is used in a loop (which is the likely scenario for a performance critical situation) and all parameters (`a` and `b` in your example) are local to the loop, then we don't have type instability, or?

**Comment by lmiq** [comment]
Exactly, it is all about the having or not non-constant global variables. 

The last example here: https://m3g.github.io/JuliaNotes.jl/stable/anonymous/#Scope-of-variables

shows how to avoid that (creating a function barrier) even if the variables where created in a global scope to begin with.
